# Generated by Django 4.0 on 2023-01-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='photo/no_image.png', upload_to='photo/%Y/%m/%d'),
        ),
    ]
